services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmyevent
    ports:
      - "5432:5432"
    volumes:
      - bookmyevent_pgdata:/var/lib/postgresql/data

volumes:
  bookmyevent_pgdata:
